# Generated by Django 3.2.6

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('روانشناسی', (('RZO', 'زوج و خانواده'), ('RKO', 'کودک'), ('RNO', 'نوجوان'), ('REK', 'اختلالات روانی'), ('RET', 'اعتیاد'), ('RFA', 'روانشناسی فردی'))), ('تحصیلی', (('TMA', 'مدارس'), ('TKO', 'کنکور سراسری'), ('TBE', 'دانشگاه های بدون آزمون'), ('TKA', 'کارشناسی ارشد'), ('TDR', 'دکتری'), ('TAZ', 'آزمون زبان'), ('TAE', 'آزمون استخدامی'), ('TAA', 'سایر آزمون ها '))), ('حقوقی', (('HKH', 'خانواده'), ('HGH', 'عقود و قرارداد ها'), ('HHO', 'حقوقی'), ('HKE', 'کیفری'), ('HTE', 'تجاری'), ('HDA', 'آیین دادرسی'), ('HMA', 'مراجع حقوقی'), ('HAH', 'آزمون های حقوقی ')))], max_length=3, verbose_name='موضوع تماس')),
                ('time_min', models.PositiveSmallIntegerField(default=0, verbose_name='مدت تماس')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='نام')),
                ('sextype', models.CharField(blank=True, choices=[('f', 'زن'), ('m', 'مرد')], max_length=1, verbose_name='جنسیت')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سن')),
                ('phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تماس')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('d', 'پیش\u200cنویس'), ('i', 'در حال بررسی'), ('p', 'تایید شده'), ('b', 'رد شده')], default='d', max_length=1, verbose_name='وضعیت')),
                ('ptime', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='زمان پیگیری')),
                ('pstatus', models.CharField(blank=True, choices=[('w', 'درحال پیگیری'), ('a', 'پیگیری انجام شد')], max_length=1, null=True, verbose_name='وضعیت پیگیری')),
                ('ptext', models.TextField(blank=True, null=True, verbose_name='توضیحات پیگیری')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to=settings.AUTH_USER_MODEL, verbose_name='مشاور')),
            ],
            options={
                'verbose_name': 'تماس',
                'verbose_name_plural': 'تماس ها',
                'ordering': ['-created'],
            },
        ),
    ]
